#!/usr/bin/env python3
"""migrate_forks.py — migrate the remaining med-agent forks into packs/.

One-shot but reproducible: for each fork it copies prompts/eval/knowledge,
extracts the routing table (engine/tools/extract_router.py), reads the OOB
KEYWORDS_* verbatim from the fork's bin/oob_check.sh (no transcription), and
emits packs/<name>/pack.yaml. Bespoke per-fork data (blocklist order + guards,
output sections, model params) is declared in CONFIGS below.

Usage: python3 engine/tools/migrate_forks.py [pack_name ...]   (default: all)
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
ENGINE = os.path.dirname(HERE)
CORE = os.path.dirname(ENGINE)
FOCUS = os.path.dirname(CORE)


def read_keywords(fork: str) -> dict:
    """Parse KEYWORDS_<NAME>="..." from a fork's oob_check.sh (join \\-continuations)."""
    raw = open(os.path.join(fork, "bin/oob_check.sh"), encoding="utf-8").read()
    joined = re.sub(r"\\\n\s*", "", raw)
    return {m.group(1): m.group(2)
            for m in re.finditer(r'^KEYWORDS_(\w+)="([^"]*)"', joined, re.MULTILINE)}


def build_blocklist(kw: dict, spec: list) -> list:
    out = []
    for rule in spec:
        if "literal" in rule:
            pattern = rule["literal"]
        else:
            pattern = "|".join(kw[v] for v in rule["vars"])
        entry = {"type": rule["type"], "pattern": pattern}
        if rule.get("unless"):
            entry["unless"] = rule["unless"]
        if rule.get("unless_all"):
            entry["unless_all"] = rule["unless_all"]
        out.append(entry)
    return out


def copy_tree(src, dst):
    if os.path.isdir(src):
        shutil.copytree(src, dst, dirs_exist_ok=True)


def migrate(cfg: dict):
    fork = os.path.join(FOCUS, cfg["fork"])
    pack = os.path.join(CORE, "packs", cfg["name"])
    adv = cfg["injection"] == "yaml_stack"
    os.makedirs(os.path.join(pack, "prompts"), exist_ok=True)
    os.makedirs(os.path.join(pack, "eval", "results"), exist_ok=True)
    os.makedirs(os.path.join(pack, "knowledge"), exist_ok=True)

    # prompts
    copy_tree(f"{fork}/prompts/sections", f"{pack}/prompts/sections")
    shutil.copy(f"{fork}/prompts/system_base.md", f"{pack}/prompts/system_base.md")
    shutil.copy(f"{fork}/prompts/output_schema.md", f"{pack}/prompts/output_schema.md")
    shutil.copy(f"{fork}/prompts/oob_templates.md", f"{pack}/prompts/oob_templates.md")
    if "doctor" in cfg["manifest"]["audiences"]:
        shutil.copy(f"{fork}/prompts/system_doctor.md", f"{pack}/prompts/system_base_doctor.md")
        shutil.copy(f"{fork}/prompts/output_schema_doctor.md", f"{pack}/prompts/output_schema_doctor.md")
        shutil.copy(f"{fork}/prompts/oob_templates_doctor.md", f"{pack}/prompts/oob_templates_doctor.md")

    # eval
    for fn in ("gold.yaml", "oob_gold.yaml", "judge_prompt.md"):
        if os.path.isfile(f"{fork}/eval/{fn}"):
            shutil.copy(f"{fork}/eval/{fn}", f"{pack}/eval/{fn}")
    for fn in cfg.get("extra_eval", []):
        if os.path.isfile(f"{fork}/eval/{fn}"):
            shutil.copy(f"{fork}/eval/{fn}", f"{pack}/eval/{fn}")
    open(f"{pack}/eval/results/.gitkeep", "w").close()

    # knowledge: yaml_stack copies the live stack to knowledge/; sections_only
    # keeps source YAML as provenance under knowledge/source/.
    if adv:
        copy_tree(f"{fork}/knowledge", f"{pack}/knowledge")
    else:
        os.makedirs(f"{pack}/knowledge/source", exist_ok=True)
        copy_tree(f"{fork}/knowledge", f"{pack}/knowledge/source")

    # routing table
    res = subprocess.run(["python3", os.path.join(HERE, "extract_router.py"),
                          f"{fork}/bin/router.sh"], capture_output=True, text=True)
    if res.returncode != 0:
        raise RuntimeError(f"extract_router failed: {res.stderr}")
    open(f"{pack}/knowledge/category_index.yaml", "w", encoding="utf-8").write(res.stdout)
    sys.stderr.write(f"  {cfg['name']}: {res.stderr.strip()}\n")

    # ingest build tools (markdown ingest packs, e.g. stcc) → engine/tools/
    for tool in cfg.get("ingest_tools", []):
        if os.path.isfile(f"{fork}/bin/{tool}"):
            shutil.copy(f"{fork}/bin/{tool}", os.path.join(HERE, tool))

    # manifest
    kw = read_keywords(fork)
    m = dict(cfg["manifest"])
    m["oob"]["blocklist"] = build_blocklist(kw, cfg["blocklist"])
    with open(f"{pack}/pack.yaml", "w", encoding="utf-8") as f:
        f.write(f"# Generated by engine/tools/migrate_forks.py from {cfg['fork']}.\n")
        yaml.safe_dump(m, f, allow_unicode=True, sort_keys=False, width=10000)
    print(f"migrated {cfg['fork']} → packs/{cfg['name']}")


# ─── per-fork configs ────────────────────────────────────────────────────────
def lite_manifest(id_, name, title, kind, header, sections, citation,
                  exempt, model_name="deepseek-chat", **extra):
    feat = {"knowledge_injection": "sections_only", "page_traceable": False,
            "ingest": extra.get("ingest", "manual"), "deep_eval": False}
    man = {
        "id": id_, "name": name, "source": {"title": title, "kind": kind},
        "audiences": ["patient"], "features": feat,
        "output_schema": "prompts/output_schema.md", "sections_dir": "prompts/sections",
        "system_base": "prompts/system_base.md", "knowledge": "knowledge/source",
        "knowledge_header": header,
        "routing": {"map": "knowledge/category_index.yaml",
                    "fallback": extra["fallback"], "llm_fallback": True},
        "oob": {"templates": "prompts/oob_templates.md", "blocklist": []},
        "output": {"oob_exempt_pattern": exempt,
                   "patient": {"required_sections": sections}},
        "model": {"name": model_name, "patient": {"temperature": 0.3, "max_tokens": 1500}},
        "eval": {"gold": "eval/gold.yaml", "oob_gold": "eval/oob_gold.yaml",
                 "judge_prompt": "eval/judge_prompt.md", "pass_threshold": 0.85,
                 "baseline": {"recorded_from": f"{extra['fork_rel']} (pre-migration); fill before deleting"}},
    }
    if "knowledge_section_title" in extra:
        man["knowledge_section_title"] = extra["knowledge_section_title"]
    if citation is not None:
        man["output"]["patient"]["citation_pattern"] = citation
    if "citation_requires" in extra:
        man["output"]["patient"]["citation_requires"] = extra["citation_requires"]
    return man


CONFIGS = [
    {  # ── neonatal (lite) ──
        "fork": "med-agent-neo", "name": "neonatal", "injection": "sections_only",
        "manifest": lite_manifest(
            "neonatal", "新生儿感染家属问答 Agent", "新生儿感染诊疗共识", "consensus",
            "以下是与用户问题相关的共识内容，你的回答必须严格基于这些内容：",
            ["【适用阶段】", "【方案要点】", "【频率", "【注意事项", "【依据】"],
            r"共识条目\s*[A-Z][0-9]+|共识第\s*[0-9A-Z]+\s*条|共识意见\s*[0-9]+|条目\s*[A-Z][0-9]+",
            "超出.*范围|不在.*共识|共识.*不覆盖|超出了.*共识",
            fallback="sepsis", fork_rel="med-agent-neo"),
        "blocklist": [
            {"type": "other_disease", "vars": ["OTHER_DISEASE"],
             "unless_all": ["坏死性小肠结肠炎|NEC", "败血症|感染|抗生素"]},
            {"type": "not_in_consensus", "vars": ["NOT_IN_CONSENSUS"]},
            {"type": "unrelated", "vars": ["WRITING"]},
            {"type": "unrelated", "vars": ["ADULT_DISEASE"], "unless": "新生儿|宝宝|婴儿|孕妇|产妇|母亲.*感染"},
            {"type": "unrelated", "vars": ["UNRELATED"], "unless": "新生儿|宝宝|婴儿|败血症|肺炎|感染"},
        ],
    },
    {  # ── sleep (lite) ──
        "fork": "med-agent-sleep", "name": "sleep", "injection": "sections_only",
        "manifest": lite_manifest(
            "sleep", "睡眠健康家属问答 Agent", "睡眠障碍诊疗指南/共识", "guideline",
            "以下是与用户问题相关的指南/共识内容，你的回答必须严格基于这些内容：",
            ["【适用人群】", "【方案要点】", "【频率", "【注意事项", "【依据】"],
            r"推荐意见第\s*[0-9]+\s*条|共识第\s*[0-9]+\s*条|指南第\s*[0-9]+\s*条|推荐意见\s*[0-9]+",
            "超出.*范围|不在.*指南|不在.*共识|指南.*不覆盖|共识.*不覆盖|超出了.*指南|超出了.*共识",
            fallback="elderly_sleep", fork_rel="med-agent-sleep"),
        "blocklist": [
            {"type": "other_disease", "vars": ["OTHER_DISEASE"]},
            {"type": "not_in_consensus", "vars": ["NOT_IN_CONSENSUS"]},
            {"type": "unrelated", "vars": ["WRITING"]},
            {"type": "unrelated", "literal": "控血糖|血糖控制|胰岛素用法|降糖药",
             "unless": "睡眠|打鼾|呼吸暂停|OSA|失眠"},
            {"type": "unrelated", "vars": ["OTHER_DISEASE_D"], "unless": "睡眠|打鼾|呼吸暂停|OSA|失眠|老年|康复"},
            {"type": "unrelated", "vars": ["UNRELATED"], "unless": "睡眠|打鼾|呼吸暂停|OSA|失眠|老年人"},
        ],
    },
    {  # ── stcc (lite + markdown ingest) ──
        "fork": "med-agent-stcc", "name": "stcc", "injection": "sections_only",
        "manifest": lite_manifest(
            "stcc", "STCC 症状分诊 Agent", "Schmitt-Thompson 临床分诊指南", "guideline",
            "以下是与用户症状相关的 STCC 分诊指南内容，你的回答必须严格基于这些内容：",
            ["【严重度判定】", "【家庭护理", "【回电", "【依据】"],
            "120|急诊|立即就医|立刻就医|紧急就医",
            "超出.*范围|不在.*指南|指南.*不覆盖|超出了.*范围|服务范围",
            fallback="abdominal_pain", fork_rel="med-agent-stcc", ingest="markdown",
            knowledge_section_title="# 当前问题相关分诊知识片段",
            citation_requires=r"【严重度判定】.*[AB]级|严重度.*[AB]级|级别.*[AB]"),
        "blocklist": [
            {"type": "diagnosis", "vars": ["DIAGNOSIS"], "unless": "怎么办|该怎么|需要.*吗|应该.*吗|去.*吗|就医|急诊|严重吗"},
            {"type": "dosage", "vars": ["DOSAGE"], "unless": "吃了.*还是|吃了.*仍然|服了.*还是|用了.*没有.*效果"},
            {"type": "unrelated", "vars": ["UNRELATED"]},
            {"type": "out_of_corpus", "vars": ["OUT_OF_CORPUS"]},
        ],
        "ingest_tools": ["extract_yaml.py", "build_sections.py"],
    },
    {  # ── psy (advanced, yaml_stack) ──
        "fork": "med-agent-psy", "name": "psy", "injection": "yaml_stack",
        "manifest": {
            "id": "psy", "name": "精神心理科 家属问答 Agent",
            "source": {"title": "DSM-5 精神障碍诊断与统计手册", "kind": "textbook"},
            "audiences": ["patient", "doctor"],
            "features": {"knowledge_injection": "yaml_stack", "page_traceable": True,
                         "ingest": "pdf", "deep_eval": True},
            "output_schema": "prompts/output_schema.md", "sections_dir": "prompts/sections",
            "system_base": "prompts/system_base.md", "knowledge": "knowledge",
            "knowledge_header": "以下是与用户问题相关的内科教材及指南内容，你的回答必须严格基于这些内容：",
            "routing": {"map": "knowledge/category_index.yaml", "fallback": "depressive:mdd", "llm_fallback": True},
            "oob": {"templates": "prompts/oob_templates.md", "blocklist": []},
            "output": {
                "oob_exempt_pattern": "超出.*范围|不在.*覆盖|不覆盖|超出了.*范围",
                "patient": {"required_sections": ["【这是什么】", "【常见表现】", "【病程与预后】", "【什么情况要尽快求助】", "【依据】"],
                            "citation_pattern": r"第[0-9]+页|p\.[0-9]+|DSM-5|页码|章节|《"},
                "doctor": {"required_sections": ["【定义与流行病学】", "【诊断要点】", "【鉴别诊断与共病】", "【风险评估与转诊】", "【参考】"],
                           "citation_pattern": r"第[0-9]+页|p\.[0-9]+|DSM-5|页码|章节|《"},
            },
            "model": {"name": "deepseek-v4-flash",
                      "patient": {"temperature": 0.3, "max_tokens": 3000},
                      "doctor": {"temperature": 0.2, "max_tokens": 4000}},
            "eval": {"gold": "eval/gold.yaml", "oob_gold": "eval/oob_gold.yaml",
                     "crisis_gold": "eval/crisis_gold.yaml",
                     "judge_prompt": "eval/judge_prompt.md", "pass_threshold": 0.85,
                     "baseline": {"recorded_from": "med-agent-psy (pre-migration); fill before deleting"}},
        },
        "blocklist": [
            {"type": "crisis", "vars": ["CRISIS"]},
            {"type": "medical_emergency", "vars": ["MED_EMERGENCY"]},
            {"type": "diagnosis", "vars": ["DIAGNOSIS"]},
            {"type": "prescription", "vars": ["PRESCRIPTION"]},
            {"type": "dosing_change", "vars": ["DOSING_CHANGE"]},
            {"type": "unrelated", "vars": ["WRITING", "FINANCE", "WEATHER", "COOKING", "TRANSLATE"]},
        ],
        "extra_eval": ["crisis_gold.yaml", "judge_prompt_doctor.md"],
    },
]


def main(argv):
    want = set(argv[1:])
    for cfg in CONFIGS:
        if want and cfg["name"] not in want:
            continue
        migrate(cfg)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
